download:
  dir: ""
  ffmpeg: "ffmpeg"
  segmentConcurrency: 6
  segmentRetries: 3
  keepSegments: false
  mode: "auto"

proxy:
  system: true
  hostname: "127.0.0.1"
  port: 2023
  skipInstallRootCert: false
  upstreamProxy: ""

target:
  appID: ""
  name: ""

cert:
  file: ""
  key: ""
  name: "Echo"
